[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComplexToys = "7b41c207-ea06-4250-aacd-19be2e667afc"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DomainColoringToy = "7cf40ad8-af6a-4ede-b3c6-2a9df3bce851"
